name: curiouscat_deleter
description: Flutter Project to delete CuriousCat tweets from your Twitter account!

version: 0.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:

  # Twitter
  twitter_oauth2_pkce: ^0.4.0
  twitter_api_v2: ^2.8.1

  # State Management
  flutter_riverpod: ^1.0.4

  # Data
  hive: ^2.2.3

  # Essentials
  path_provider: ^2.0.11
  flutter_dotenv: ^5.0.2

  # UI
  sizer: ^2.0.15
  lottie: ^1.3.0
  cached_network_image: ^3.2.1
  countup: ^0.1.4
  flutter_animate: ^1.0.0

  # Icons
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - .env


fonts:
  - family: Cairo
    fonts:
      - asset: assets/fonts/Cairo-ExtraLight.ttf
        weight: 100
      - asset: assets/fonts/Cairo-Light.ttf
        weight: 200
      - asset: assets/fonts/Cairo-Regular.ttf
        weight: 300
      - asset: assets/fonts/Cairo-Medium.ttf
        weight: 400
      - asset: assets/fonts/Cairo-SemiBold.ttf
        weight: 500
      - asset: assets/fonts/Cairo-Bold.ttf
        weight: 600
      - asset: assets/fonts/Cairo-ExtraBold.ttf
        weight: 700
      - asset: assets/fonts/Cairo-Black.ttf
        weight: 900
